<?php
declare(strict_types=1);
require_once __DIR__ . '/client-inc.php';
$client = client_portal_require_client();
$assets = client_portal_grouped_assets((int)$client['client_id']);
$clientName = (string)($client['dba_name'] ?: $client['legal_name']);
function status_badge(string $status): string { return '<span class="badge">' . client_portal_h($status) . '</span>'; }
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Assets | <?= client_portal_h(APP_NAME) ?></title><link rel="stylesheet" href="<?= client_portal_h(BASE_URL) ?>/css/portal_shell.css?v=7"><style>.wrap{max-width:1180px;margin:auto;padding:18px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:14px}.card{padding:18px}.badges{display:grid;gap:8px;margin:12px 0}.badge{display:inline-flex;padding:7px 10px;border-radius:999px;border:1px solid var(--glass-border);background:var(--glass-bg-soft);font-weight:700}.meta{color:var(--muted);font-size:.92rem}.actions{display:flex;gap:10px;flex-wrap:wrap}.btn{width:auto}</style></head><body><main class="wrap"><section class="glass card"><h1><?= client_portal_h($clientName) ?> asset protection</h1><p class="meta">Read-only visibility from cached OPS telemetry. The portal does not call vendor APIs or show raw vendor payloads.</p><div class="actions"><a class="btn btn-secondary" href="<?= client_portal_h(BASE_URL) ?>/client-backups.php?client_id=<?= (int)$client['client_id'] ?>">Backup protection</a></div></section><section class="grid" aria-label="Asset protection cards"><?php foreach ($assets as $asset): $vendors=$asset['vendors']; ?><article class="glass card"><h2><?= client_portal_h((string)$asset['device_name']) ?></h2><p class="meta"><?= client_portal_h((string)($asset['os_name'] ?: $asset['username'] ?: 'Cached device')) ?></p><div class="badges"><div>DNS Filtering: <?= status_badge(client_portal_public_status($vendors['scoutdns'] ?? null)) ?></div><div>Endpoint Security: <?= status_badge(client_portal_public_status($vendors['huntress'] ?? null)) ?></div><div>Antivirus/Defender: <?= status_badge(client_portal_public_status($vendors['defender'] ?? null)) ?></div><div>Backup Protection: <?= status_badge(client_portal_public_status($vendors['cove'] ?? null)) ?></div></div><a class="btn btn-primary" href="<?= client_portal_h(BASE_URL) ?>/client-asset.php?client_id=<?= (int)$client['client_id'] ?>&asset=<?= rawurlencode((string)$asset['key']) ?>">View details</a></article><?php endforeach; ?><?php if (!$assets): ?><article class="glass card"><h2>No cached telemetry yet</h2><p class="meta">Protection status will appear after OPS cache syncs normalized vendor status.</p></article><?php endif; ?></section></main></body></html>
