<?php
declare(strict_types=1);
require_once __DIR__ . '/inc/bootstrap.php';
require_once __DIR__ . '/inc/client_portal.php';
$client = client_portal_require_client();
$asset = client_portal_asset_by_key((int)$client['client_id'], (string)($_GET['asset'] ?? ''));
if (!$asset) { http_response_code(404); echo 'Asset not found.'; exit; }
$vendors = $asset['vendors'];
$labels = ['scoutdns'=>'DNS Filtering', 'huntress'=>'Endpoint Security', 'cove'=>'Backup Protection'];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= client_portal_h((string)$asset['device_name']) ?> | <?= client_portal_h(APP_NAME) ?></title><link rel="stylesheet" href="<?= client_portal_h(BASE_URL) ?>/css/portal_shell.css?v=7"><style>.wrap{max-width:980px;margin:auto;padding:18px}.card{padding:18px;margin:0 0 14px}.rows{display:grid;gap:12px}.row{display:grid;grid-template-columns:1fr auto;gap:10px;padding:14px;border:1px solid var(--glass-border);border-radius:14px}.status{font-weight:800}.meta{color:var(--muted)}@media(max-width:700px){.row{grid-template-columns:1fr}}</style></head><body><main class="wrap"><section class="glass card"><p><a href="<?= client_portal_h(BASE_URL) ?>/client-assets.php?client_id=<?= (int)$client['client_id'] ?>">&larr; All assets</a></p><h1><?= client_portal_h((string)$asset['device_name']) ?></h1><p class="meta">Safe client-facing status only. Raw vendor JSON and internal debug data are not exposed.</p></section><section class="glass card"><h2>Protection details</h2><div class="rows"><?php foreach ($labels as $code=>$label): $row=$vendors[$code]??null; ?><article class="row"><div><strong><?= client_portal_h($label) ?></strong><div class="meta"><?= $row ? client_portal_h((string)($row['status_detail'] ?: $row['status_label'] ?: 'Cached status')) : 'No included cached status for this asset.' ?></div></div><div class="status"><?= client_portal_h(client_portal_public_status($row)) ?></div></article><?php endforeach; ?><article class="row"><div><strong>Antivirus/Defender</strong><div class="meta">Shown only when already available in cached asset data.</div></div><div class="status">Unknown</div></article></div></section></main></body></html>
