CREATE TABLE `InvoicePayment` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` ENUM('PENDING','POSTED','VOIDED') NOT NULL DEFAULT 'PENDING',
  `method` ENUM('ACH_BANK','CARD') NOT NULL,
  `processorReference` VARCHAR(191) NULL,
  `grossAmount` DECIMAL(10,2) NOT NULL,
  `feeAmount` DECIMAL(10,2) NULL,
  `netAmount` DECIMAL(10,2) NULL,
  `receivedAt` DATETIME(3) NULL,
  `postedAt` DATETIME(3) NULL,
  `voidedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `invoiceId` BIGINT UNSIGNED NOT NULL,
  `accountingJournalId` BIGINT UNSIGNED NULL,
  `createdById` BIGINT UNSIGNED NOT NULL,
  `postedById` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `InvoicePayment_processorReference_key` (`processorReference`),
  UNIQUE INDEX `InvoicePayment_accountingJournalId_key` (`accountingJournalId`),
  INDEX `InvoicePayment_invoiceId_status_createdAt_idx` (`invoiceId`,`status`,`createdAt`),
  CONSTRAINT `InvoicePayment_invoiceId_fkey` FOREIGN KEY (`invoiceId`) REFERENCES `WorkOrderInvoice`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `InvoicePayment_accountingJournalId_fkey` FOREIGN KEY (`accountingJournalId`) REFERENCES `AccountingJournal`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `InvoicePayment_createdById_fkey` FOREIGN KEY (`createdById`) REFERENCES `OpsUser`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `InvoicePayment_postedById_fkey` FOREIGN KEY (`postedById`) REFERENCES `OpsUser`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
