CREATE TABLE `work_order_expenses` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category` ENUM('MATERIAL', 'TRAVEL', 'PARKING_TOLL', 'EQUIPMENT_RENTAL', 'OTHER') NOT NULL DEFAULT 'OTHER',
  `description` VARCHAR(255) NOT NULL,
  `cost_amount` DECIMAL(10, 2) NOT NULL,
  `bill_amount` DECIMAL(10, 2) NULL,
  `occurred_at` DATETIME(3) NULL,
  `notes` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  `voided_at` DATETIME(3) NULL,
  `work_order_id` BIGINT UNSIGNED NOT NULL,
  `created_by_id` BIGINT UNSIGNED NOT NULL,
  `voided_by_id` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `work_order_expenses_work_order_id_voided_at_occurred_at_idx` (`work_order_id`, `voided_at`, `occurred_at`),
  INDEX `work_order_expenses_created_by_id_created_at_idx` (`created_by_id`, `created_at`),
  CONSTRAINT `work_order_expenses_work_order_id_fkey` FOREIGN KEY (`work_order_id`) REFERENCES `work_orders`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `work_order_expenses_created_by_id_fkey` FOREIGN KEY (`created_by_id`) REFERENCES `ops_users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `work_order_expenses_voided_by_id_fkey` FOREIGN KEY (`voided_by_id`) REFERENCES `ops_users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `work_order_materials` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `source` ENUM('PURCHASE', 'INVENTORY_PULL', 'OTHER') NOT NULL DEFAULT 'PURCHASE',
  `description` VARCHAR(255) NOT NULL,
  `sku` VARCHAR(100) NULL,
  `quantity` DECIMAL(10, 3) NOT NULL,
  `unit_cost` DECIMAL(10, 2) NOT NULL,
  `unit_price` DECIMAL(10, 2) NULL,
  `notes` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  `voided_at` DATETIME(3) NULL,
  `work_order_id` BIGINT UNSIGNED NOT NULL,
  `created_by_id` BIGINT UNSIGNED NOT NULL,
  `voided_by_id` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `work_order_materials_work_order_id_voided_at_created_at_idx` (`work_order_id`, `voided_at`, `created_at`),
  INDEX `work_order_materials_created_by_id_created_at_idx` (`created_by_id`, `created_at`),
  CONSTRAINT `work_order_materials_work_order_id_fkey` FOREIGN KEY (`work_order_id`) REFERENCES `work_orders`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `work_order_materials_created_by_id_fkey` FOREIGN KEY (`created_by_id`) REFERENCES `ops_users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `work_order_materials_voided_by_id_fkey` FOREIGN KEY (`voided_by_id`) REFERENCES `ops_users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
