<?php
// Internal OPS QR generator for public MMIT URLs.
// No secrets. Uses qrserver.com to generate preview/download images, so only use this for non-sensitive public URLs.
$presets = [
    'Keith digital card' => 'https://midwestmanagedit.com/qr.php?code=keith_card',
    'Company digital card' => 'https://midwestmanagedit.com/qr.php?code=company_card',
    'Schedule a Chat' => 'https://midwestmanagedit.com/qr.php?code=schedule',
    'Main website' => 'https://midwestmanagedit.com/qr.php?code=website',
];
$default = $presets['Keith digital card'];
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="noindex,nofollow">
  <title>MMIT QR Generator</title>
  <style>
    :root{--bg:#061326;--panel:#0d1f3d;--text:#eaf1ff;--muted:#aebbd3;--line:rgba(148,163,184,.25);--blue:#2563eb;--purple:#7c3aed}
    *{box-sizing:border-box} body{margin:0;min-height:100vh;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;color:var(--text);background:radial-gradient(circle at 20% 12%,rgba(37,99,235,.35),transparent 28rem),linear-gradient(135deg,#07162c,#030814)}
    .wrap{width:min(100%,980px);margin:0 auto;padding:32px 18px}.panel{border:1px solid var(--line);border-radius:26px;background:rgba(13,31,61,.88);box-shadow:0 24px 70px rgba(0,0,0,.35);padding:24px}
    h1{margin:0 0 8px;font-size:clamp(2rem,5vw,3rem);letter-spacing:-.05em}.lead{margin:0 0 24px;color:var(--muted);line-height:1.55}.grid{display:grid;grid-template-columns:1.1fr .9fr;gap:22px}@media(max-width:780px){.grid{grid-template-columns:1fr}}
    label{display:block;margin:14px 0 7px;font-weight:800;color:#cfe2ff} input,select{width:100%;border:1px solid var(--line);border-radius:14px;background:#061326;color:var(--text);font-size:1rem;padding:12px 13px}
    .presets{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:12px 0}.btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;min-height:44px;padding:11px 14px;border:1px solid var(--line);border-radius:14px;background:rgba(255,255,255,.06);color:var(--text);text-decoration:none;font-weight:800;cursor:pointer}.btn.primary{background:linear-gradient(90deg,var(--blue),var(--purple));border-color:rgba(255,255,255,.18)}
    .actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:16px}.preview{display:grid;place-items:center;padding:18px;border:1px solid var(--line);border-radius:22px;background:#fff}.preview img{max-width:100%;height:auto;display:block}.note{font-size:.9rem;color:var(--muted);line-height:1.5;margin-top:16px}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;color:#9cc8ff;word-break:break-all}
  </style>
</head>
<body>
  <main class="wrap">
    <section class="panel">
      <h1>MMIT QR Generator</h1>
      <p class="lead">Internal helper for creating QR codes for public Midwest Managed IT links. Do not use for private/client data because the preview image is generated by a third-party QR image service.</p>
      <div class="grid">
        <div>
          <label for="data">QR value</label>
          <input id="data" value="<?= htmlspecialchars($default, ENT_QUOTES) ?>">

          <div class="presets">
            <?php foreach ($presets as $label => $url): ?>
              <button class="btn preset" type="button" data-url="<?= htmlspecialchars($url, ENT_QUOTES) ?>"><?= htmlspecialchars($label) ?></button>
            <?php endforeach; ?>
          </div>

          <label for="size">Size</label>
          <select id="size">
            <option value="512">512 × 512</option>
            <option value="768">768 × 768</option>
            <option value="1024" selected>1024 × 1024</option>
          </select>

          <label for="ecc">Error correction</label>
          <select id="ecc">
            <option value="L">L - small</option>
            <option value="M">M - medium</option>
            <option value="Q">Q - high</option>
            <option value="H" selected>H - highest</option>
          </select>

          <div class="actions">
            <button class="btn primary" type="button" id="refresh">Refresh QR</button>
            <button class="btn" type="button" id="copy">Copy value</button>
            <a class="btn" id="download" href="#" download="mmit-qr.png">Download PNG</a>
          </div>
          <p class="note">Recommended printed QR targets use <span class="mono">/qr.php?code=...</span> so landing pages can change later without reprinting.</p>
        </div>
        <div>
          <div class="preview"><img id="qr" alt="Generated QR code"></div>
          <p class="note mono" id="current"></p>
        </div>
      </div>
    </section>
  </main>
  <script>
    const data = document.getElementById('data');
    const size = document.getElementById('size');
    const ecc = document.getElementById('ecc');
    const qr = document.getElementById('qr');
    const download = document.getElementById('download');
    const current = document.getElementById('current');

    function buildUrl() {
      const s = size.value;
      const value = encodeURIComponent(data.value.trim() || 'https://midwestmanagedit.com/');
      return `https://api.qrserver.com/v1/create-qr-code/?size=${s}x${s}&ecc=${ecc.value}&margin=16&data=${value}`;
    }
    function refresh() {
      const url = buildUrl();
      qr.src = url;
      download.href = url;
      current.textContent = data.value.trim();
    }
    document.getElementById('refresh').addEventListener('click', refresh);
    document.getElementById('copy').addEventListener('click', async () => {
      await navigator.clipboard.writeText(data.value.trim());
      alert('Copied.');
    });
    document.querySelectorAll('.preset').forEach(btn => btn.addEventListener('click', () => { data.value = btn.dataset.url; refresh(); }));
    data.addEventListener('input', refresh); size.addEventListener('change', refresh); ecc.addEventListener('change', refresh);
    refresh();
  </script>
</body>
</html>
