CREATE TABLE `FieldNationImport` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `messageId` VARCHAR(191) NOT NULL,
  `sender` VARCHAR(191) NULL,
  `subject` VARCHAR(255) NULL,
  `receivedAt` DATETIME(3) NULL,
  `rawText` LONGTEXT NOT NULL,
  `status` ENUM('RECEIVED','PARSED','REVIEW_REQUIRED','CONVERTED','REJECTED') NOT NULL DEFAULT 'RECEIVED',
  `sourceReference` VARCHAR(191) NULL,
  `title` VARCHAR(255) NULL,
  `location` VARCHAR(255) NULL,
  `scheduledAt` DATETIME(3) NULL,
  `grossPay` DECIMAL(10,2) NULL,
  `estimatedHours` DECIMAL(8,2) NULL,
  `mileage` DECIMAL(10,2) NULL,
  `score` DECIMAL(5,2) NULL,
  `parsedData` JSON NULL,
  `workOrderId` BIGINT UNSIGNED NULL,
  `createdById` BIGINT UNSIGNED NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `FieldNationImport_messageId_key` (`messageId`),
  UNIQUE INDEX `FieldNationImport_workOrderId_key` (`workOrderId`),
  INDEX `FieldNationImport_status_createdAt_idx` (`status`,`createdAt`),
  INDEX `FieldNationImport_sourceReference_idx` (`sourceReference`),
  CONSTRAINT `FieldNationImport_workOrderId_fkey` FOREIGN KEY (`workOrderId`) REFERENCES `WorkOrder`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FieldNationImport_createdById_fkey` FOREIGN KEY (`createdById`) REFERENCES `OpsUser`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
