<?php
declare(strict_types=1);
require_once __DIR__.'/../inc/bootstrap.php';require_login();
require_once __DIR__.'/../inc/field_gig_tracker.php';
$h=static fn($v):string=>htmlspecialchars(is_scalar($v)?(string)$v:'',ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
$pdo=db();$uid=(int)(current_user()['user_id']??0);$ready=false;$error='';$p=null;$c=null;$errors=[];$form=[];$vehicles=[];$history=[];
try{gig_ready($pdo);$ready=true;$vehicles=field_tracker_rows($pdo,'SELECT vehicle_id,vehicle_name FROM field_vehicles WHERE active=1 ORDER BY is_primary DESC,vehicle_id');}catch(Throwable $e){$error=$e instanceof PDOException?'Run the Gig tracker staging migration first.':$e->getMessage();}
if($ready&&$_SERVER['REQUEST_METHOD']==='POST'){
 csrf_validate_or_die();
 try{
  if(($_POST['action']??'')==='preview'){
   unset($_SESSION['gig_preview']);$f=$_FILES['tracker_file']??[];
   if(($f['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||!is_string($f['tmp_name']??null)||!is_uploaded_file($f['tmp_name']))throw new InvalidArgumentException('Choose a JSON export; check the server upload limit if upload fails.');
   $raw=file_get_contents($f['tmp_name'],false,null,0,FIELD_TRACKER_MAX_BYTES+1);if(!is_string($raw))throw new InvalidArgumentException('Unable to read export.');
   $p=gig_parse($raw,date_default_timezone_get());$c=gig_vehicle($pdo,(int)($_POST['vehicle_id']??0));$errors=gig_conflicts($pdo,$p,(int)$c['vehicle']['vehicle_id']);
   if(!$errors)$_SESSION['gig_preview']=['raw'=>$raw,'timezone'=>date_default_timezone_get(),'vehicle_id'=>(int)$c['vehicle']['vehicle_id'],'fingerprint'=>$c['fingerprint'],'user_id'=>$uid,'expires'=>time()+1800,'token'=>bin2hex(random_bytes(24))];
  }elseif(($_POST['action']??'')==='apply'){
   $t=$_SESSION['gig_preview']??null;if(!is_array($t)||!is_string($_POST['preview_token']??null)||!hash_equals($t['token'],$_POST['preview_token']))throw new InvalidArgumentException('No matching preview. Upload again.');
   if(($_POST['confirm_review']??'')!=='1')throw new InvalidArgumentException('Confirm that you reviewed the values and warnings.');
   $form=$_POST;$sid=gig_apply($pdo,$t,$form,$uid);unset($_SESSION['gig_preview']);$_SESSION['gig_flash']=$sid;header('Location: '.BASE_URL.'/admin/field_gig_tracker.php');exit;
  }else throw new InvalidArgumentException('Choose Preview or Create shift.');
 }catch(InvalidArgumentException|JsonException $e){$error=$e->getMessage();}catch(Throwable $e){error_log('Gig import failed: '.get_class($e).' '.$e->getCode());$error='Import failed; no partial shift was retained. Upload again and report repeated failures.';}
}
if($ready&&$p===null&&isset($_SESSION['gig_preview'])){
 try{$t=$_SESSION['gig_preview'];if($t['expires']<time()||$t['user_id']!==$uid)throw new RuntimeException('Expired');$p=gig_parse($t['raw'],$t['timezone']);$c=gig_vehicle($pdo,$t['vehicle_id']);$errors=gig_conflicts($pdo,$p,$t['vehicle_id']);}catch(Throwable $e){unset($_SESSION['gig_preview']);$error='Preview expired or changed. Upload again.';$p=null;}
}
$success=(int)($_SESSION['gig_flash']??0);unset($_SESSION['gig_flash']);
if($ready)$history=field_tracker_rows($pdo,'SELECT shift_id,applied_at FROM field_gig_tracker_imports WHERE shift_id IS NOT NULL ORDER BY import_id DESC LIMIT 8');
$money=['base_ride_earnings'=>'Ride earnings (excluding tips and bonuses)','tips'=>'Tips','bonuses'=>'Bonuses','adjustments'=>'Adjustments (+ / −)','toll_reimbursements'=>'Toll reimbursements','platform_fees'=>'Platform fees (informational)','direct_trip_costs'=>'Direct trip costs'];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Import rideshare tracker · OPS staging</title>
<style>body{margin:0;background:#081726;color:#edf4ff;font:16px/1.5 system-ui,sans-serif}main{max-width:1100px;margin:32px auto;padding:0 20px}h1{font-size:34px;margin:4px 0}h2{font-size:21px}a{color:#9acaff}.top{display:flex;justify-content:space-between;align-items:center;gap:16px}.card{background:#192a3d;border:1px solid #3b5067;border-radius:16px;padding:22px;margin:20px 0}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.metric{background:#0d2033;padding:14px;border-radius:10px}.metric strong{display:block;font-size:24px}label{display:block;margin:12px 0 6px}input,select,textarea,button{box-sizing:border-box;font:inherit;border:1px solid #71869d;border-radius:8px;padding:10px;background:#0b1a2c;color:inherit}input:not([type=checkbox]),select,textarea{width:100%}button,.btn{background:#235f9b;cursor:pointer;color:white;padding:12px;border-radius:8px;text-decoration:none}button{margin-top:18px}table{width:100%;border-collapse:collapse}td,th{text-align:left;border-bottom:1px solid #3b5067;padding:10px}.scroll{overflow:auto}.warn,.error,.success{padding:16px;border-radius:9px;margin:12px 0}.warn{background:#382b12;border:1px solid #cb9c46}.error{background:#351e2b;border:1px solid #e16e7c}.success{background:#123b32;border:1px solid #4bba9f}.muted{color:#b5c9e1}.small{font-size:14px}fieldset{border:0;padding:0;margin:0}legend{font-size:20px;font-weight:700;margin-top:20px}@media(max-width:700px){.grid{grid-template-columns:1fr}.top{display:block}h1{font-size:28px}}</style></head><body><main>
<div class="top"><div><span class="muted">STAGING · LYFT + UBER</span><h1>Import rideshare tracker</h1></div><a class="btn" href="<?= $h(BASE_URL) ?>/admin/field_rideshare.php">Back to Gig Work</a></div>
<?php if($error):?><div class="error" role="alert"><?= $h($error) ?></div><?php endif;?>
<?php if($success):?><div class="success">Created unposted shift #<?= $success ?>. No accounting journal was posted. <a href="<?= $h(BASE_URL) ?>/admin/field_rideshare.php?edit=<?= $success ?>">Review shift</a></div><?php endif;?>
<?php if($ready):?><section class="card"><h2>1. Choose the outing and vehicle</h2><form method="post" enctype="multipart/form-data"><?= csrf_field() ?><input type="hidden" name="action" value="preview"><input type="hidden" name="MAX_FILE_SIZE" value="<?= FIELD_TRACKER_MAX_BYTES ?>"><label for="vehicle">Vehicle</label><select id="vehicle" name="vehicle_id" required><?php foreach($vehicles as $v):?><option value="<?= (int)$v['vehicle_id'] ?>"><?= $h($v['vehicle_name']) ?></option><?php endforeach;?></select><label for="export">Completed tracker JSON</label><input id="export" name="tracker_file" type="file" accept=".json,application/json" required><p class="muted">Preview is read-only. This pilot creates new shifts; it does not merge existing shifts. Preview expires after 30 minutes.</p><button>Preview export</button></form></section><?php endif;?>
<?php if($p!==null):$zone=new DateTimeZone($p['timezone']);?><section class="card"><h2>2. Review <?= $h($p['platform']) ?> · <?= $h($c['vehicle']['vehicle_name']) ?></h2><p class="small muted">Outing <?= $h($p['id']) ?> · <?= $h($p['timezone']) ?></p>
<?php foreach($errors as $e):?><div class="error"><?= $h($e) ?></div><?php endforeach;?>
<div class="warn"><ul><?php foreach($p['warnings']as $w):?><li><?= $h($w) ?></li><?php endforeach;?></ul></div>
<?php if(!empty($p['closing_note'])):?><div class="success"><strong>Tracker closing note</strong><br><?= nl2br($h($p['closing_note'])) ?></div><?php endif;?>
<div class="grid"><div class="metric">Door-to-door miles<strong><?= $h($p['total_miles']) ?></strong><?= $h($p['start_odometer']) ?> → <?= $h($p['home_odometer']) ?></div><div class="metric">Online / return-home minutes<strong><?= $p['online_minutes'] ?> / <?= $p['deadhead_minutes'] ?></strong><?= $p['break_minutes'] ?> break minutes excluded</div><div class="metric">Completed / lost queued rides<strong><?= $p['completed_rides'] ?> / <?= $p['lost_rides'] ?></strong>Lost entries add no booked time</div></div>
<div class="scroll"><table><tbody><?php foreach(['start'=>'Started','offline'=>'Went offline','home'=>'Arrived home']as $key=>$label):?><tr><th><?= $label ?></th><td><?= $h(field_tracker_datetime($p[$key],$zone)) ?></td></tr><?php endforeach;?><tr><th>Booked / passenger minutes</th><td><?= $p['booked_minutes'] ?> / <?= $p['passenger_minutes'] ?></td></tr><tr><th>Accepted / auto-queued entries</th><td><?= $p['acquisition']['MANUAL_ACCEPT'] ?> / <?= $p['acquisition']['AUTO_QUEUE'] ?></td></tr></tbody></table></div>
<h3>GPS segments — comparison only</h3><p class="small muted">Measured portions may not cover the full route. Missing miles are not filled from the odometer.</p><div class="grid"><?php foreach(['pickup'=>'Travel to pickup','passenger'=>'Passenger','home'=>'Offline to home']as $key=>$label):?><div class="metric"><?= $label ?><strong><?= $p['gps'][$key]===null?'Unavailable':$h(number_format($p['gps'][$key],2)).' mi' ?></strong><?= $h(round($p['coverage_seconds'][$key]/60,1)) ?> minutes of GPS links</div><?php endforeach;?></div>
<?php if(!$errors&&isset($_SESSION['gig_preview'])):?><h2>3. Confirm mileage and earnings</h2><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="apply"><input type="hidden" name="preview_token" value="<?= $h($_SESSION['gig_preview']['token']) ?>"><p><strong>Offline odometer = home odometer − return-home miles.</strong> Enter reviewed mileage; use 0 explicitly for an intentional stationary test. Booked miles include pickup travel and passenger miles.</p><div class="grid"><?php foreach(['deadhead_miles'=>'Offline-to-home miles (one decimal)','booked_miles'=>'Booked miles (pickup + passenger)','passenger_miles'=>'Passenger miles']as $key=>$label):?><div><label for="<?= $key ?>"><?= $label ?></label><input id="<?= $key ?>" name="<?= $key ?>" type="number" min="0" step="<?= $key==='deadhead_miles'?'0.1':'0.01' ?>" value="<?= $h($form[$key]??'') ?>" required></div><?php endforeach;?></div><p id="mile-summary" class="muted" aria-live="polite"></p>
<fieldset><legend>Driver earnings from the platform summary</legend><p class="small muted">The tracker does not receive payments. Enter driver earnings, separating tips and bonuses. Platform fees are informational, matching Gig Work.</p><div class="grid"><?php foreach($money as $key=>$label):?><div><label for="<?= $key ?>"><?= $label ?></label><input id="<?= $key ?>" name="<?= $key ?>" type="number" step="0.01" <?= $key==='adjustments'?'':'min="0"' ?> value="<?= $h($form[$key]??'') ?>" required></div><?php endforeach;?></div></fieldset>
<label for="payout">Payout destination</label><select id="payout" name="payout_destination" required><option value="">Choose destination</option><?php foreach(['LYFT_DIRECT'=>'Lyft Direct','PERSONAL_BANK'=>'Personal bank','PNC'=>'PNC','OTHER'=>'Other']as $key=>$label):?><option value="<?= $key ?>" <?= ($form['payout_destination']??'')===$key?'selected':'' ?>><?= $label ?></option><?php endforeach;?></select><label for="reason">Review reason / notes</label><textarea id="reason" name="review_reason" maxlength="1000" required><?= $h($form['review_reason']??'') ?></textarea><label><input type="checkbox" name="confirm_review" value="1" required> I reviewed the timestamps, mileage split, earnings and warnings. Create this new shift.</label><p class="small muted">Vehicle cost: $<?= $h(number_format($c['model']['all_in_cpm'],4)) ?>/mile. Saved unposted; no accounting journal is created.</p><button>Create reviewed Gig Work shift</button></form>
<script>const d=document.getElementById('deadhead_miles');function showMiles(){const n=Number(d.value),total=<?= json_encode($p['total_miles']) ?>,home=<?= json_encode($p['home_odometer']) ?>;document.getElementById('mile-summary').textContent=d.value!==''&&n>=0&&n<=total?'Derived offline odometer: '+(home-n).toFixed(1)+' · Online '+(total-n).toFixed(1)+' + return '+n.toFixed(1)+' = '+total.toFixed(1)+' miles.':'';}d.addEventListener('input',showMiles);showMiles();</script>
<?php endif;?></section><?php endif;?>
<?php if($history):?><section class="card"><h2>Recent imports</h2><ul><?php foreach($history as $row):?><li><a href="<?= $h(BASE_URL) ?>/admin/field_rideshare.php?edit=<?= (int)$row['shift_id'] ?>">Shift #<?= (int)$row['shift_id'] ?></a> · <?= $h($row['applied_at']) ?></li><?php endforeach;?></ul></section><?php endif;?>
</main></body></html>
